### ISSUE TITLE
crash in math when building footman

### ISSUE THREAD

**Issue by joseppi** [LazyFoxStudio/Project-2#14]
[
![image](https://user-images.githubusercontent.com/23116728/38745862-1b3c7f14-3f46-11e8-920a-1c1ce0c67773.png)
](url)

**Comment by rodrigodpl** [comment]
there are too many methods that call Point1 - Point 2. Next time, try to follow the code until a relevant piece so we can find where exactly the bug is

**Comment by joseppi** [comment]
ok!
