### ISSUE TITLE
Health bars not centered

### ISSUE THREAD

**Issue by joseppi** [LazyFoxStudio/Project-2#16]

**Comment by Adria-F** [comment]
Life bars are too much to the right.
![imagen](https://user-images.githubusercontent.com/23353263/38756664-966ca208-3f6a-11e8-88d6-4ae4b2ce5a44.png)

**Comment by joseppi** [comment]
This happens when the mage collides with a forest. The life bar keeps going forward but the collider of the mage stays the same
