### ISSUE TITLE
HP Healthbars

### ISSUE THREAD

**Issue by joseppi** [LazyFoxStudio/Project-2#163]
![](https://cdn.discordapp.com/attachments/411950298194640906/450258400664879105/unknown.png)

There are too many health bars on display and you can barely see the entities fighting each other. Posible solutions:
- Make the health bars smaller
- Only displaying them when they are begin hurt by a short period of time.
- Make the health bars only appear when selecting the squad.

**Comment by Adria-F** [comment]
We have already talked about this issue many times.

- It doesn't bother that much.
- It is really difficult that anyone has that many troops in a normal game.
- With the current attack speed, displaying them by a short period would cause them to be there all the time as it is right now. Or if the time is to short to look too epileptic and distracting.
- When you select the squad, you already see the detailed life on the menu. The "in-game" life bars are suposed to be a help so they payer can easily and as fast as possible see the average life of each troop.
- Making them smaller doesn't change anything, the problem would be more with the height than the width and the height is already pretty small. If we make it thinner, it could be barely seen with a quick look (as we want it to be).
