### ISSUE TITLE
Important balance

### ISSUE THREAD

**Issue by Adria-F** [LazyFoxStudio/Project-2#187]
The hero scaling is to high.
- At late game he can easily instakill 20 grunts with mage Q
- Juggernauts are suposed to be so tanky, but with mage W you can remove half of the life

Grunts don't deal almost any damage in comparison with axe throwers

**Comment by Witiza** [comment]
we are working on it

**Comment by joseppi** [comment]
The late game q of the mage was expected so the player can feel his hero is progressing since there is an improvement in his stats while the game goes on.

**Comment by Adria-F** [comment]
The producer told us, that he felt that the hero had too much importance, so, it shouldn't be able to clean a wave at late game.
It also makes the game too easy, it should be hard to reach 20 min of gameplay.

**Comment by joseppi** [comment]
He also told us that the hero had to have some kind of progress so he can feel he is going forward. The fact that at the beginning you can't kill grunts and later on you can, makes you feel that progress.
