### ISSUE TITLE
Screen doesn't go down with the mouse moving down

### ISSUE THREAD

**Issue by morgadoCV** [LazyFoxStudio/Project-2#69]
Reproduce it by trying to go down with your mouse

![image](https://user-images.githubusercontent.com/17145449/39699759-d161f438-51fa-11e8-8dee-fedc9fcd87a4.png)

**Comment by MaxitoSama** [comment]
You have checked an old version of the game, gomenasai!

**Comment by MaxitoSama** [comment]
Try it in full screen and it will work perfectly
