### ISSUE TITLE
Crash on attack

### ISSUE THREAD

**Issue by JoanValiente** [LazyFoxStudio/Project-2#99]
![asdasaaaaa](https://user-images.githubusercontent.com/25648776/39700084-2fd5ecbc-51fc-11e8-8e4d-8b88caf9f978.PNG)

Well, that.
It happened the moment that archers where supposed to attack the death knights.

**Comment by MaxitoSama** [comment]
You have checked an old version of the game, gomenasai! The attack is completely different now!
